//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Caracteristique
{
    private static int nextId = 0;

    private int id;

    public int Id
    {
        get { return id; }
        set { id = value; }
    }

    private string nom;

    public string Nom
    {
        get { return nom; }
        set { nom = value; }
    }


    private string description;

    public string Description
    {
        get { return description; }
        set { description = value; }
    }

    public Caracteristique()
    {
        this.id = nextId;
        nextId++;
    }

	
}

