//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Categorie : Personnage
{


    private string nomCategorie;

    public string NomCategorie
    {
        get { return nomCategorie; }
        set { nomCategorie = value; }
    }


    private string description;

    public string Description
    {
        get { return description; }
        set { description = value; }
    }
    public Categorie() : base() { }
}

