//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Combat : Situation
{

    private Personnage pnj;

    public Personnage Pnj
    {
        get { return pnj; }
        set { pnj = value; }
    }

    private List<Competence> competencesPossibles;

    public List<Competence> CompetencesPossibles
    {
        get { return competencesPossibles; }
        set { competencesPossibles = value; }
    }

    public Combat() : base() { }

    public Combat(Personnage pnj)
    {
        this.pnj = pnj;
    }


}

