//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Dialogue : Situation
{


    private string message;

    public string Message
    {
        get { return message; }
        set { message = value; }
    }


    public Dialogue(string message) : base()
    {
        Choix continuer = new Choix("Continuer");
        continuer.Difficulte = 0;
        this.ChoixPossibles.Add(continuer);
        this.Difficulte = 0;
        this.message = message; 
    }

    public Dialogue()
    {
        
    }

}

