//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class InstanceCaracteristique
{

    private string niveau;

    public string Niveau
    {
        get { return niveau; }
        set { niveau = value; }
    }

    private Caracteristique caracteristique;

    public Caracteristique Caracteristique
    {
        get { return caracteristique; }
        set { caracteristique = value; }
    }




}

