//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Univers
{

    private string nom;
    public string Nom
	{
		get;
		set;
	}

    private string description;

    public string Description
    {
        get { return description; }
        set { description = value; }
    }

    private List<Equipement> equipements;

    public List<Equipement> Equipements
    {
        get { return equipements; }
        set { equipements = value; }
    }

    private List<Categorie> categories;

    public List<Categorie> Categories
    {
        get { return categories; }
        set { categories = value; }
    }

    private List<Situation> situations;
    public List<Situation> Situations
    {
        get { return situations; }
        set { situations = value; }
    }


    private List<Competence> competences;
    public List<Competence> Competences
    {
        get { return competences; }
        set { competences = value; }
    }


    private List<Caracteristique> caracteristiques;
    public List<Caracteristique> Caracteristiques
    {
        get { return caracteristiques; }
        set { caracteristiques = value; }
    }

    public Univers(){
        this.caracteristiques = new List<Caracteristique>();
        this.competences = new List<Competence>();
        this.situations = new List<Situation>();
        this.categories = new List<Categorie>();
        this.equipements = new List<Equipement>();
    }

    public void ajouterCararacteristique(Caracteristique c)
    {
        this.caracteristiques.Add(c);
    }

    public void ajouterCompetence(Competence c)
    {
        this.competences.Add(c);
    }
    public void ajouterSituation(Situation s)
    {
        this.situations.Add(s);
    }
    public void ajouterCategorie(Categorie c) 
    {
        this.categories.Add(c);
    }
    public void ajouterEquipement(Equipement e)
    {
        this.equipements.Add(e);
    }
}

